### ISSUE TITLE
IVS type registration needs clearer reference and change controller

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/haptics#3]
The current document refers to an ISO document list, not to a specific ISO document.
Even if it is a draft, it should link directly to the document.

The change controller should be either IESG (on behalf of ISO) or ISO SC29 WG2 (if they want to be it).

**Comment by drykm** [comment]
FIXED.

Change controller for IVS changed to ISO/IEC JTC1/SC 29/WG 7 (MPEG 3D Graphics and Haptics Coding WG), the specific group in charge of specifying the MPEG Haptics Coding standard (ISO/IEC 23090-31), in which IVS is used. The full specification of IVS is currently published in ISO/IEC JTC1/SC 29/WG 2 N0072, so that is listed as the published specification, but 23090-31 will also have the full definition of IVS in the appendix eventually, and WG 7 is indeed the correct entity to be the change controller for IVS. 

This change has been made in v04 of the haptics I-D, available here: https://datatracker.ietf.org/doc/draft-ietf-mediaman-haptics/04/

**Comment by alvestrand** [comment]
Thank you. Verified as fixed.
